apiVersion: v2
name: gpp-publicatiebank
description: Een registratie die voorziet in de "Openbare Documenten opslag"-functionaliteiten

type: application
version: 2.0.1
appVersion: 0.1.0

dependencies:
  - name: redis
    version: 20.2.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
