apiVersion: v2
name: gpp-app
description: A helm chart for the ICATT GPP app.

type: application

# Chart version 
version: 0.1.0
appVersion: 0.0.0

dependencies:
  - name: redis
    version: 20.2.1
    repository: https://charts.bitnami.com/bitnami
    tags:
      - redis
