{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpp-burgerportaal.fullname" . }}
  labels:
    {{- include "gpp-burgerportaal.labels" . | nindent 4 }}
stringData:
  POSTGRES_PASSWORD: {{ .Values.settings.database.password | toString | quote }}
  ODRC_API_KEY: {{ .Values.settings.gppPublicatiebank.apiKey | toString |  quote }}
  {{- if .Values.settings.oidc.clientSecret }}
  OIDC_CLIENT_SECRET: {{ .Values.settings.oidc.clientSecret | toString | quote }}
  {{- end }}
  SEARCH_API_KEY: {{ .Values.settings.search.apiKey | toString |  quote }}
{{- end }}
