apiVersion: v2
name: gpp-stack
description: An umbrella chart for the GPP stack

type: application

# Chart version
version: 0.2.2

appVersion: "0.1.0"

dependencies:
  - name: openzaak
    version:  1.8.2
    repository: https://maykinmedia.github.io/charts/
    condition: openzaak.enabled

  - name: gpp-app
    version: 0.2.0
    repository: https://GPP-Woo.github.io/charts
    condition: gpp-app.enabled

  - name: gpp-publicatiebank
    version: 2.0.5
    repository: https://GPP-Woo.github.io/charts
    condition: gpp-publicatiebank.enabled

  - name: gpp-burgerportaal
    version: 1.1.0
    repository: https://GPP-Woo.github.io/charts
    condition: gpp-burgerportaal.enabled

  - name: gpp-zoeken
    version: 0.2.2
    repository: https://GPP-Woo.github.io/charts
    condition: gpp-zoeken.enabled
