global:
  settings:
    # -- Global databasehost, overrides setting.database.host
    databaseHost: ""

gpp-publicatiebank: 
  enabled: true
  redis:
    nameOverride: "gpp-publicatiebank-redis"

gpp-app:
  enabled: true

gpp-burgerportaal:
  enabled: true

gpp-zoeken:
  enabled: true
  redis:
    nameOverride: "gpp-zoeken-redis"
  # eck-operator subchart
  eck-operator:
    enabled: true
    nameOverride: "gpp-zoeken-eck-operator"
    fullnameOverride: "gpp-zoeken-eck-operator"

  # eck-elasticsearch subchart
  eck-elasticsearch:
    enabled: true
    nameOverride: "gpp-zoeken-eck-elasticsearch"
    fullnameOverride: "gpp-zoeken-eck-elasticsearch"


openzaak:
  enabled: true

  # Redis subchart
  redis:
    nameOverride: "openzaak-redis"
    # FIXME
    # This is needed because gpp-publicatiebank has a newer redis chart version
    # and the labels are shared globally. When OZ redis chart version is upgraded, this
    # can be removed.
    sentinel:
      masterService:
        enabled: false
