{{- if .Values.pdb.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gpp-publicatiebank.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "gpp-publicatiebank.labels" . | nindent 4 }}
spec:
  {{- if .Values.pdb.minAvailable }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gpp-publicatiebank.selectorLabels" . | nindent 6 }}
{{- end }}