{{- if and ((.Values.settings.elasticsearch).user) (.Values.settings.elasticsearch.password) }}
apiVersion: v1
kind: Secret
metadata:
  name: zoeken-elastic-secret
  labels:
    {{- include "gpp-zoeken.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.settings.elasticsearch.user }}
  password: {{ .Values.settings.elasticsearch.password }}
  roles: {{ default "superuser" .Values.settings.elasticsearch.role }}
{{- end }}
