{{- if not .Values.existingSecretElastic }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gpp-zoeken.fullname" . }}-elastic
  labels:
    {{- include "gpp-zoeken.labels" . | nindent 4 }}
stringData:
  username: {{ .Values.settings.elastic.user }}
  password: {{ .Values.settings.elastic.password }}
  roles: {{ .Values.settings.elastic.roles }}
{{- end }}
