apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpp-zoeken.fullname" . }}
  labels:
    {{- include "gpp-zoeken.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "gpp-zoeken.selectorLabels" . | nindent 4 }}
---
{{- if .Values.flower.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpp-zoeken.flowerFullname" . }}
  labels:
    {{- include "gpp-zoeken.flowerLabels" . | nindent 4 }}
spec:
  type: {{ .Values.flower.service.type }}
  ports:
    - port: {{ .Values.flower.service.port }}
      targetPort: 5555
      protocol: TCP
      name: http
  selector:
    {{- include "gpp-zoeken.flowerSelectorLabels" . | nindent 4 }}
{{- end }}