global:
  settings:
    # -- Global databasehost, overrides setting.database.host
    databaseHost: ""

replicaCount: 1

image:
  repository: "ghcr.io/gpp-woo/gpp-burgerportaal"
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""
  automountServiceAccountToken: true

podAnnotations: {}

podLabels: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 1000

livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

readinessProbe:
  initialDelaySeconds: 30
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 6
  successThreshold: 1

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  className: ""
  # -- ingress hosts
  hosts: []
  #  - host: gpp-burgerportaal.gemeente.nl
  #    paths:
  #      - path: /
  #        pathType: ImplementationSpecific
  tls: []
  #  - secretName: gpp-burgerportaal-tls
  #    hosts:
  #      - gpp-burgerportaal.gemeente.nl


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 200m
  #   memory: 256Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

pdb:
  create: false
  minAvailable: 1
  maxUnavailable: ""

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  # -- If persistence is enabled, a PVC is used. Otherwise, the app container will use an emptyDir volume. Note: data in emptyDir volumes is lost when the pod is removed.
  enabled: true
  # -- If persistence.existingClaim is set, no PVC will be created, but the referenced PVC will be used to mount a volume in the app container.
  existingClaim: null
  size: 1Gi
  storageClassName: ""
  accessMode: ReadWriteMany

settings:
  # -- Whether to block robots from crawling the citizen portal. <details><summary>More information</summary> If set to `true`, a `robots.txt` file will be served with the content `User-agent: *\nDisallow: /`, which blocks all robots from crawling the citizen portal. Default value is `false`.</details>
  blockRobots: false
  # -- The number of hours the sitemap is cached. <br/> (default value is `23`)
  sitemapCacheDurationHours: 23
  # -- The maximum duration in minutes for downloading files. <br/> (default value is `10`)
  downloadTimeoutMinutes: 10

  database:
    host: ""
    port: 5432
    username: ""
    password: ""
    name: ""

  gppPublicatiebank:
    # -- The secret key for the Publicatiebank to establish a connection. <details> <summary>More information </summary>For example: `VM2B!ccnebNe.M*gxH63*NXc8iTiAGhp`</details>
    apiKey: ""
    # -- The base URL of the Publicatiebank to establish a connection. <details> <summary>More information </summary>For example: `https://publicatiebank.mijn-gemeente.nl` </details>
    baseUrl: ""

  oidc:
    # -- The role that will be used to determine if a user is an administrator in the citizen portal. <details> <summary>More information </summary>For example: `admin`</details>
    adminRole: ""
    # -- The OpenID Connect authority of the Identity Provider to establish a connection. <details> <summary>More information </summary>For example: `https://auth.mijn-gemeente.nl/realms/gpp` </details>
    authority: ""
    # -- The client ID for the OpenID Connect connection. <details> <summary>More information </summary>For example: `gpp-burgerportaal`</details>
    clientId: ""
    # -- The client secret for the OpenID Connect connection. <details> <summary>More information </summary>For example: `VM2B!ccnebNe.M*gxH63*NXc8iTiAGhp`</details>
    clientSecret: ""
    # -- The claim type in which the user roles are stored. <details> <summary>More information </summary>For example: `roles`</details>
    roleClaimType: ""
    # -- The claim type in which the user ID is stored. <details> <summary>More information </summary>For example: `sub`</details>
    idClaimType: ""
    # -- The claim type in which the user name is stored. <details> <summary>More information </summary>For example: `name`</details>
    nameClaimType: ""

  search:
    # -- The secret key for the Search component to establish a connection. <details> <summary>More information </summary>For example: `VM2B!ccnebNe.M*gxH63*NXc8iTiAGhp`</details>
    apiKey: ""
    # -- The base URL of the Search component to establish a connection. <details> <summary>More information </summary>For example: `https://zoekcomponent.mijn-gemeente.nl` </details>
    baseUrl: ""

  resources:
    # -- The title of the citizen portal. <details><summary>More information</summary> For example: Open Mijn Gemeente</details>
    portaalTitel: ""
    # -- DEPRECATED - use resources.organisatieNaam instead. this setting will be removed in a future version
    gemeenteNaam: ""
    # -- DEPRECATED - this setting is managed in the application and will be removed in a future version
    gemeenteLogoUrl: ""
    # -- DEPRECATED - this setting is managed in the application and will be removed in a future version
    gemeenteFaviconUrl: ""
    # -- DEPRECATED - this setting is managed in the application and will be removed in a future version
    gemeenteMainImageUrl: ""
    # -- DEPRECATED - use resources.designTokensUrl instead. this setting will be removed in a future version
    gemeenteDesignTokensUrl: ""
    # -- DEPRECATED - use resources.webFontSources instead . this setting will be removed in a future version
    gemeenteWebFontSources: []
    # -- DEPRECATED - use resources.themeNaam instead. this setting will be removed in a future version
    gemeenteThemeNaam: ""
    # -- DEPRECATED - this setting is managed in the application and will be removed in a future version
    gemeenteWebsiteUrl: ""
    # -- DEPRECATED - this setting is managed in the application and will be removed in a future version
    gemeentePrivacyUrl: ""
    # -- DEPRECATED - this setting is managed in the application and will be removed in a future version
    gemeenteContactUrl: ""
    # -- DEPRECATED - this setting is managed in the application and will be removed in a future version
    gemeenteWelkom: ""
    # -- DEPRECATED - this setting is managed in the application and will be removed in a future version
    gemeenteVideoUrl: ""
    # -- DEPRECATED - this setting is managed in the application and will be removed in a future version
    toegankelijkheidsverklaringRegisterUrl: ""

    # -- Public URL where the CSS file containing NL Design System tokens is available, to style the citizen portal in the organisational house style. <details><summary>More information </summary>For example: `https://unpkg.com/@gemeente/design-tokens/dist/index.css`</details>
    designTokensUrl: ""
    # -- The name of the organisation used within the citizen portal. <details><summary>More information</summary> For example: My Organization. Please note: only mention the name here, not the type (so “Demodam” instead of Gemeente Demodam”)</details> 
    organisatieNaam: ""
    # -- The type of organisation used within the citizen portal. <details><summary>More information</summary> Possible values: `gemeente`, `provincie`, `waterschap`, `stichting`, `vereniging`, `organisatie`. This determines how the organization is referred to in the Citizen Portal (e.g. "Naar de gemeente" or "Naar het waterschap"). Default: `organisatie`. </details> 
    organisatieType: ""
    # -- The name of the selector from the CSS file used to scope the NLDS tokens. <details><summary>More information</summary> For example: `gemeente-theme` </details>
    themeNaam: ""
    # -- Public URLs referring to web font file(s) associated with the organisation house style. <details><summary>More information </summary>For example: `["https://fonts.mijn-gemeente.nl/custom-regular-font.woff2", "https://fonts.mijn-gemeente.nl/custom-bold-font.woff2"]`. A single reference to the location where all font-style files are stored is also possible: `["https://fonts.mijn-gemeente.nl/custom-font/"]`. **Note:** this configuration is only intended to allow font files to be loaded under CORS. References to files must also be specified under a `@font-face` ruleset in the theme styling.</details>
    webFontSources: []

  aspnetcore:
    forwardedHeadersEnabled: true
    environment: ""
    httpPorts: ""

# -- Optionally specify extra list of additional volumes, for example to trust extra ca certificates.
extraVolumes: []
# e.g:
# extraVolumes:
#   - name: my-secret-mount
#     secret:
#       secretName: my-secret-containing-my-custom-ca

# -- Optionally specify extra list of additional volumeMounts, for example to trust extra ca certificates.
extraVolumeMounts: []
# e.g:
# extraVolumeMounts:
#  - name: my-secret-mount
#    readOnly: true
#    subPath: ca.crt
#    mountPath: /etc/ssl/certs/my-custom-ca.crt
